import { createRequire } from 'module';
import path from 'path';
// Static imports (not createRequire) so Vercel's file tracer ships these packages with the function.
import KuroshiroModule from 'kuroshiro';
import KuromojiAnalyzerModule from 'kuroshiro-analyzer-kuromoji';
// On'yomi for kanji kuroshiro's dictionary doesn't know. Generated by scripts/generate-kanji-readings.cjs.
import kanjiOn from './kanji-on.json';

const Kuroshiro = (KuroshiroModule as any).default ?? KuroshiroModule;
const KuromojiAnalyzer = (KuromojiAnalyzerModule as any).default ?? KuromojiAnalyzerModule;

// Resolve the dictionary relative to the kuromoji package, not process.cwd(), which differs on Vercel.
const require = createRequire(import.meta.url);
const dictPath = path.join(path.dirname(require.resolve('kuromoji/package.json')), 'dict') + '/';

let kuroshiro: any = null;
let initialized = false;
let initPromise: Promise<void> | null = null;

async function getKuroshiro() {
	if (initialized && kuroshiro) return kuroshiro;
	if (initPromise) {
		await initPromise;
		return kuroshiro;
	}

	initPromise = (async () => {
		try {
			const k = new Kuroshiro();
			await k.init(new KuromojiAnalyzer({ dictPath }));
			kuroshiro = k;
			initialized = true;
		} catch (e) {
			initPromise = null;
			throw e;
		}
	})();

	await initPromise;
	return kuroshiro;
}

export async function romanize(text: string): Promise<string> {
	if (!/[\u3000-\u303f\u3040-\u309f\u30a0-\u30ff\uff00-\uff9f\u4e00-\u9faf\u3400-\u4dbf]/.test(text)) {
		return text;
	}

	const k = await getKuroshiro();
	let result = await k.convert(text, { to: 'romaji', mode: 'spaced', romajiSystem: 'hepburn' });

	result = result
		.replace(/ā/g, 'aa').replace(/Ā/g, 'Aa')
		.replace(/ī/g, 'ii').replace(/Ī/g, 'Ii')
		.replace(/ū/g, 'uu').replace(/Ū/g, 'Uu')
		.replace(/ē/g, 'ee').replace(/Ē/g, 'Ee')
		.replace(/ō/g, 'ou').replace(/Ō/g, 'Ou');

	// kuroshiro passes unknown kanji through as-is, one token each (e.g. 戮辱 -> "戮 辱"). Rejoin
	// each run and read it character by character, so 戮辱 becomes "rikujoku".
	result = result.replace(/[\u3400-\u4dbf\u4e00-\u9fff\uf900-\ufaff](?: ?[\u3400-\u4dbf\u4e00-\u9fff\uf900-\ufaff])*/g, (run: string) =>
		' ' + [...run.replace(/ /g, '')].map((c) => (kanjiOn as Record<string, string>)[c] ?? c).join('') + ' '
	);

	return result.replace(/\s+/g, ' ').replace(/ ([,.!?)\]])/g, '$1').trim().replace(/\b\w/g, (c: string) => c.toUpperCase());
}